<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Letsgo</name>
   <tag></tag>
   <elementGuidId>7cf1a4cc-d688-4249-94a1-9beb77ec0777</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mip-button.mip-button--primary.mip-button--big</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-0']/mip-onboarding-home/div/div[2]/div[2]/div/mip-button[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8617d014-7871-4f0e-abda-e0af5b9572eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mip-button mip-button--primary mip-button--big</value>
      <webElementGuid>675967a3-312e-404b-9372-0d0747ae273c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Lets'go!</value>
      <webElementGuid>bb6405e9-a80d-4e99-a93b-fd7347e1be18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/mip-onboarding-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mip-onboarding&quot;]/div[@class=&quot;mip-onboarding__main-content&quot;]/div[2]/div[@class=&quot;mip-onboarding__button ng-star-inserted&quot;]/mip-button[@class=&quot;ng-star-inserted&quot;]/button[@class=&quot;mip-button mip-button--primary mip-button--big&quot;]</value>
      <webElementGuid>d9aa4955-6ba3-45b0-8846-2b53d74bd916</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/mip-onboarding-home/div/div[2]/div[2]/div/mip-button[2]/button</value>
      <webElementGuid>5906341f-6797-48fc-9ddd-41f7ec6cf81f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go back'])[1]/following::button[1]</value>
      <webElementGuid>b8cc607c-c965-428c-8280-9bbe70055516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy policy.'])[1]/following::button[2]</value>
      <webElementGuid>ecdca0db-857c-48ee-a0f4-8228b1184fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mip-button[2]/button</value>
      <webElementGuid>38cf5057-5896-4d02-8f6f-76fd1a3aabaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = concat(&quot; Lets&quot; , &quot;'&quot; , &quot;go!&quot;) or . = concat(&quot; Lets&quot; , &quot;'&quot; , &quot;go!&quot;))]</value>
      <webElementGuid>bc2c8faf-6df6-4232-803c-06eaaea10bd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
