<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_navigate_before</name>
   <tag></tag>
   <elementGuidId>c46b53bb-8dd0-45e2-8adf-0c46b7cbb532</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mip-menu__collapse-item.ng-tns-c70-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>59024961-c4a0-4eb3-b357-ac07942f7b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mip-menu__collapse-item ng-tns-c70-0</value>
      <webElementGuid>d1653320-65f9-4028-a7b5-75ffdf38b83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>navigate_before</value>
      <webElementGuid>e1745bf7-50e6-4ba7-81ec-fbd6675b5105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;mip-app&quot;]/div[@class=&quot;mip-app__main-row&quot;]/mip-menu[@class=&quot;ng-tns-c70-0&quot;]/div[@class=&quot;ng-tns-c70-0 mip-menu mip-menu--collapse&quot;]/div[@class=&quot;ng-tns-c70-0&quot;]/div[@class=&quot;mip-menu__collapse-item ng-tns-c70-0&quot;]</value>
      <webElementGuid>ffb76928-1546-4a7b-be58-368131074940</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::div[4]</value>
      <webElementGuid>40023968-0a4c-40a2-8438-357ae6c11f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='by NTT DATA'])[1]/following::div[4]</value>
      <webElementGuid>a7564277-106d-4454-adcf-a48130d7eeb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::div[3]</value>
      <webElementGuid>033170af-d300-4fcb-90a0-de3c1c2e9753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Market Information'])[1]/preceding::div[5]</value>
      <webElementGuid>94eb56fc-2a33-4ec8-82a7-87b70da7578c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mip-menu/div/div/div</value>
      <webElementGuid>12e383d8-41d8-4161-a497-b26435169028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'navigate_before' or . = 'navigate_before')]</value>
      <webElementGuid>1ae390bf-45f3-4a12-9f4d-3ebc8d8d2a11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
