<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MartechAdtech</name>
   <tag></tag>
   <elementGuidId>50209f37-f0d0-46f0-a543-c8d1a5b2f2f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Coming soon'])[3]/following::div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a79358f7-c5ac-46cb-a056-55cc9fca8eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mip-innovation-trend__cards__card__body__title</value>
      <webElementGuid>3b616a95-dc27-4bcd-b667-89ba8adb1e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Martech/Adtech</value>
      <webElementGuid>aa5cf168-e3a7-4715-978b-a98637d6a238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;mip-app&quot;]/div[@class=&quot;mip-app__main-row&quot;]/div[@class=&quot;mip-app__main-row__main-column&quot;]/div[@class=&quot;mip-app__main-row__main-column__content&quot;]/mip-innovation-trends[@class=&quot;ng-star-inserted&quot;]/mip-innovations-trends-ntt-data[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mip-dashboard&quot;]/div[@class=&quot;mip-dashboard__row--biggest&quot;]/div[@class=&quot;mip-innovation-trend__cards&quot;]/div[@class=&quot;mip-innovation-trend__cards__card ng-star-inserted&quot;]/div[@class=&quot;mip-innovation-trend__cards__card__body&quot;]/div[@class=&quot;mip-innovation-trend__cards__card__body__title&quot;]</value>
      <webElementGuid>c406ac74-6432-4803-a1db-15fb65f202b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coming soon'])[3]/following::div[3]</value>
      <webElementGuid>25337630-db0f-4fd1-9f9d-46ce9ed43cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find out why Customer Data Platforms'])[1]/following::div[3]</value>
      <webElementGuid>a3cbaf1f-20d4-4b51-856e-04e9a675c968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('', '&quot;', 'MarTech', '&quot;', '')])[1]/preceding::div[1]</value>
      <webElementGuid>738bba0a-ce42-4120-a82c-aff892009725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('', '&quot;', 'AdTech', '&quot;', '')])[1]/preceding::div[1]</value>
      <webElementGuid>89213fe1-cfba-46d9-b475-0d277b7e07ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Martech/Adtech']/parent::*</value>
      <webElementGuid>fc03f081-2d12-40c6-885f-87d9fab76ff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div</value>
      <webElementGuid>27b73f09-5701-48d7-bf51-0e12a0126e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Martech/Adtech' or . = 'Martech/Adtech')]</value>
      <webElementGuid>c0c678ff-535e-47ac-9ee4-c1a9756ec52f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
