<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Revenue</name>
   <tag></tag>
   <elementGuidId>8133be95-5c42-4411-9668-55198985d6a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-sort-header-content.ng-tns-c116-27</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Year'])[1]/following::div[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b0a1d474-4b04-4aab-935e-8774c5416b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-sort-header-content ng-tns-c116-27</value>
      <webElementGuid>a8ab2852-a3ae-46d4-8812-db31cfe21d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Revenue</value>
      <webElementGuid>9a75253a-5226-420e-8b73-89a5eee08566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;mip-app&quot;]/div[@class=&quot;mip-app__main-row&quot;]/div[@class=&quot;mip-app__main-row__main-column&quot;]/div[@class=&quot;mip-app__main-row__main-column__content&quot;]/mip-company-detail[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mip-dashboard ng-star-inserted&quot;]/div[@class=&quot;mip-dashboard__row--big&quot;]/mip-section[@class=&quot;mip-section--big&quot;]/div[@class=&quot;mip-section mip-section--big&quot;]/mip-competitors-financial-performance-table[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mip-table&quot;]/mip-table[@class=&quot;ng-tns-c125-25 ng-star-inserted&quot;]/table[@class=&quot;mat-table cdk-table mat-sort ng-tns-c125-25 mip-table&quot;]/thead[1]/tr[@class=&quot;mat-header-row cdk-header-row ng-tns-c125-25 ng-star-inserted&quot;]/th[@class=&quot;mat-sort-header mat-header-cell cdk-header-cell ng-tns-c116-27 cdk-column-revenue mat-column-revenue ng-tns-c125-25 align-end ng-star-inserted cdk-focused cdk-mouse-focused&quot;]/div[@class=&quot;mat-sort-header-container mat-focus-indicator ng-tns-c116-27&quot;]/div[@class=&quot;mat-sort-header-content ng-tns-c116-27&quot;]</value>
      <webElementGuid>08d7bf66-3a8e-4889-8678-6aba30ff6698</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year'])[1]/following::div[8]</value>
      <webElementGuid>50dc682f-7b02-42af-8b99-b0a921108927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Innovation Services.'])[1]/following::div[16]</value>
      <webElementGuid>c71128f4-0ebe-42b0-872d-91e9c626f878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gross profit'])[1]/preceding::div[7]</value>
      <webElementGuid>4779bfe1-aecd-4dae-b3f8-71b6176247fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operating income'])[1]/preceding::div[15]</value>
      <webElementGuid>74742b4c-9b23-448d-a3d3-9f5b47c7ec8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Revenue']/parent::*</value>
      <webElementGuid>7004855c-6ccc-4c0c-8900-ad163b29397d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/div/div</value>
      <webElementGuid>8378ac38-fb39-4f15-8831-b13a1aa6d4b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Revenue' or . = 'Revenue')]</value>
      <webElementGuid>8381c9e8-65fa-4075-a1c0-5f23d49f65ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
