<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_5G</name>
   <tag></tag>
   <elementGuidId>71663892-4c4c-48f6-bc9d-10195fcef289</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Coming soon'])[9]/following::div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e06a7042-8f87-4541-bae1-259e654298ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mip-innovation-trend__cards__card__body__title</value>
      <webElementGuid>e057aa8b-209f-4e4e-8fdb-2a857caa60d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5G</value>
      <webElementGuid>a3693b6c-b16e-44d6-a9e6-9f9972094810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;mip-app&quot;]/div[@class=&quot;mip-app__main-row&quot;]/div[@class=&quot;mip-app__main-row__main-column&quot;]/div[@class=&quot;mip-app__main-row__main-column__content&quot;]/mip-innovation-trends[@class=&quot;ng-star-inserted&quot;]/mip-innovations-trends-ntt-data[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mip-dashboard&quot;]/div[@class=&quot;mip-dashboard__row--biggest&quot;]/div[@class=&quot;mip-innovation-trend__cards&quot;]/div[@class=&quot;mip-innovation-trend__cards__card ng-star-inserted&quot;]/div[@class=&quot;mip-innovation-trend__cards__card__body&quot;]/div[@class=&quot;mip-innovation-trend__cards__card__body__title&quot;]</value>
      <webElementGuid>94b87c4b-17e6-4908-b7f7-9c8e5191fcd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coming soon'])[9]/following::div[3]</value>
      <webElementGuid>b25dbc64-3928-4fcd-a6ac-3df50130c4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find out why Blockchain'])[1]/following::div[3]</value>
      <webElementGuid>382980e9-d32e-45ca-b37a-7d93aad276c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='see more'])[13]/preceding::div[3]</value>
      <webElementGuid>87ba2689-a651-4fdf-8ec1-2a7ed44e9f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5G']/parent::*</value>
      <webElementGuid>0c583e96-1ef1-4b00-afa5-d32d526b509a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div</value>
      <webElementGuid>85182051-8912-487a-a2aa-f6fed15c28f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '5G' or . = '5G')]</value>
      <webElementGuid>880dda93-44bf-4fad-9d9c-70b2d5523848</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
