<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_competitors_mip-searcher__content__in_a5650d</name>
   <tag></tag>
   <elementGuidId>f8d25038-f812-4b57-85fe-063c5f0ebcad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mip-searcher-basic/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.mip-searcher__content__input.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa60ef6f-e860-4677-b67f-41f2215ba2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mip-searcher__content__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>be1bfd41-b61c-4dfb-afbd-8a9599bcbeb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search a competitor</value>
      <webElementGuid>f1d70030-51ae-47c4-93fe-efcfef85c719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;mip-app&quot;]/div[@class=&quot;mip-app__main-row&quot;]/div[@class=&quot;mip-app__main-row__main-column&quot;]/div[@class=&quot;mip-app__main-row__main-column__content&quot;]/mip-companies[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mip-dashboard mip-competitors-landing&quot;]/div[@class=&quot;mip-dashboard__row--biggest&quot;]/mip-section[@class=&quot;mip-section--big mip-competitors-landing__header&quot;]/div[@class=&quot;mip-section mip-section--big&quot;]/div[@class=&quot;mip-companies__search ng-star-inserted&quot;]/mip-searcher[1]/div[@class=&quot;mip-searcher__box mip-searcher__box__focus&quot;]/div[@class=&quot;mip-searcher mip-searcher--focus mip-searcher--focus-and-dropdown&quot;]/mip-searcher-with-dropdown-back[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mip-searcher__dropdown-container&quot;]/mip-searcher-basic[1]/div[@class=&quot;mip-searcher__content&quot;]/input[@class=&quot;mip-searcher__content__input ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>681fbc6c-c480-49c4-b18c-e83db87286fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mip-searcher-basic/div/input</value>
      <webElementGuid>623c0185-b925-4fea-998a-a66b2e69738d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search a competitor']</value>
      <webElementGuid>ede91e25-819b-486e-af2a-67338cccfc7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
