<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_navigate_before</name>
   <tag></tag>
   <elementGuidId>1a93c36e-57a4-44dc-b5aa-721859b38ad4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.mip-menu__collapse-item__button__icon.ng-tns-c70-0.material-icons.mat-ligature-font.mat-icon-no-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::mat-icon[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>8aead121-aa9a-49c2-b5c5-b5056462dc51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4994e7c3-341f-4c35-a25e-f8ebab4e6d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate mip-menu__collapse-item__button__icon ng-tns-c70-0 material-icons mat-ligature-font mat-icon-no-color</value>
      <webElementGuid>f8c937a2-b616-4d7a-b077-f7ed836ea77f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9e0e56fc-6bb8-4f64-a536-7f8fd6fdfb20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>c0ff4c3f-6b5c-4110-be38-68b266599ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>navigate_before</value>
      <webElementGuid>11d3a97a-f60f-45b6-a995-24ee9db26800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;mip-app&quot;]/div[@class=&quot;mip-app__main-row&quot;]/mip-menu[@class=&quot;ng-tns-c70-0&quot;]/div[@class=&quot;ng-tns-c70-0 mip-menu mip-menu--collapse&quot;]/div[@class=&quot;ng-tns-c70-0&quot;]/div[@class=&quot;mip-menu__collapse-item ng-tns-c70-0&quot;]/div[@class=&quot;mip-menu__collapse-item__button ng-tns-c70-0&quot;]/mat-icon[@class=&quot;mat-icon notranslate mip-menu__collapse-item__button__icon ng-tns-c70-0 material-icons mat-ligature-font mat-icon-no-color&quot;]</value>
      <webElementGuid>482502c9-4ffe-44b4-8091-17ec6c01a1f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::mat-icon[2]</value>
      <webElementGuid>05f8ed2c-511a-483f-a9c6-25d0541ccffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='by NTT DATA'])[1]/following::mat-icon[3]</value>
      <webElementGuid>1b982717-e510-48ac-a821-2c3fc503617a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::mat-icon[3]</value>
      <webElementGuid>b7b7baf5-d28f-4652-93ac-7bfd20371b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Market Information'])[1]/preceding::mat-icon[3]</value>
      <webElementGuid>eea1dfe6-2bf5-43a4-b3b2-8f86d9580ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='navigate_before']/parent::*</value>
      <webElementGuid>989e680f-9adc-4a7a-9299-c7c2724764e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/mat-icon</value>
      <webElementGuid>c9f31990-98b8-40c5-bbc4-46873d6599c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'navigate_before' or . = 'navigate_before')]</value>
      <webElementGuid>849b4a03-bfc2-4dab-be99-6246fbf950d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
