<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Terms of use_mat-checkbox-inner-container</name>
   <tag></tag>
   <elementGuidId>839c4e86-bcb3-4990-a927-f064389d7db2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-checkbox[@id='privacy']/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#privacy > label.mat-checkbox-layout > span.mat-checkbox-inner-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>93457f44-9dd8-432f-bfe0-3709ccea14ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-checkbox-inner-container</value>
      <webElementGuid>3c457bb2-3f3b-43b9-a4ec-41f1bad81e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;privacy&quot;)/label[@class=&quot;mat-checkbox-layout&quot;]/span[@class=&quot;mat-checkbox-inner-container&quot;]</value>
      <webElementGuid>6a8a9f6e-3c40-433d-97e2-b6a924be2e88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='privacy']/label/span</value>
      <webElementGuid>2db46dd3-1353-48b7-b975-5281cf6f87cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of use.'])[1]/following::span[1]</value>
      <webElementGuid>dd9687b7-0c83-4d38-82f5-fe25b9307c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy policy.'])[1]/preceding::span[7]</value>
      <webElementGuid>5ab5fcbe-0cef-4db3-9c05-ca18a4b7ef48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-checkbox[2]/label/span</value>
      <webElementGuid>7586c2a3-25e7-4fe6-9054-ec12a4da7867</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
