<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_I have read and agree to the Privacy policy</name>
   <tag></tag>
   <elementGuidId>fc1f2a7b-2ea1-47ee-bacc-ea371d6dc2eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#privacy > label.mat-checkbox-layout > span.mat-checkbox-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-checkbox[@id='privacy']/label/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>492b7bc0-63fb-4631-859a-c5199d476853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-checkbox-label</value>
      <webElementGuid>0bd9c8c7-7582-440a-84c0-5b8cdfa5f2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  I have read and agree to the Privacy policy. </value>
      <webElementGuid>201e3456-1cd5-4923-9b25-140fdae728d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;privacy&quot;)/label[@class=&quot;mat-checkbox-layout&quot;]/span[@class=&quot;mat-checkbox-label&quot;]</value>
      <webElementGuid>bd7e54f9-d2e3-4d5f-aefe-0dc91258a99b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='privacy']/label/span[2]</value>
      <webElementGuid>fa9ae1e2-e2de-49c1-ae42-a8d8a68ee468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of use.'])[1]/following::span[7]</value>
      <webElementGuid>924611e4-4a95-4848-8bd4-a6f6e5099c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::span[2]</value>
      <webElementGuid>10697c4a-1bc4-454a-be92-f07ea68a1dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='I have read and agree to the']/parent::*</value>
      <webElementGuid>04bbab0f-b77f-4b7e-aa63-d22ad73a64dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-checkbox[2]/label/span[2]</value>
      <webElementGuid>69b9e981-e9f8-4d4f-b10d-62bc34d562d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '  I have read and agree to the Privacy policy. ' or . = '  I have read and agree to the Privacy policy. ')]</value>
      <webElementGuid>020936c6-44a2-4665-aa39-61bea9de7f44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
