<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Accenture</name>
   <tag></tag>
   <elementGuidId>0e483935-ab20-4cd8-b7dd-f154cb068e7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mip-competitors-landing__table-section__name-column__name__label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Revenue (last updated)'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2d7d92e1-eb24-4df0-bbd2-8dae32dc7cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mip-competitors-landing__table-section__name-column__name__label</value>
      <webElementGuid>ef44f620-39f5-4055-b4c7-7a5fb608703a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accenture</value>
      <webElementGuid>8508f0ac-4535-421c-91b3-67a22e20c3ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;mip-app&quot;]/div[@class=&quot;mip-app__main-row&quot;]/div[@class=&quot;mip-app__main-row__main-column&quot;]/div[@class=&quot;mip-app__main-row__main-column__content&quot;]/mip-companies[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mip-dashboard mip-competitors-landing&quot;]/div[@class=&quot;mip-dashboard__row--biggest&quot;]/mip-section[@class=&quot;mip-section--big landing mip-competitors-landing__table-section&quot;]/div[@class=&quot;mip-section mip-section--big&quot;]/div[@class=&quot;mip-table ng-star-inserted&quot;]/div[@class=&quot;tableContainer&quot;]/mip-table[@class=&quot;ng-tns-c125-1 ng-star-inserted&quot;]/table[@class=&quot;mat-table cdk-table mat-sort ng-tns-c125-1 mip-table&quot;]/tbody[1]/tr[@class=&quot;mat-row cdk-row ng-tns-c125-1 ng-star-inserted&quot;]/td[@class=&quot;mat-cell cdk-cell cdk-column-organizationName mat-column-organizationName ng-tns-c125-1 ng-star-inserted&quot;]/div[@class=&quot;mip-competitors-landing__table-section__name-column ng-star-inserted&quot;]/a[@class=&quot;mip-competitors-landing__table-section__name-column__name&quot;]/span[@class=&quot;mip-competitors-landing__table-section__name-column__name__label&quot;]</value>
      <webElementGuid>aed40152-1ae2-4b37-abf4-34b0f3a7ee48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revenue (last updated)'])[1]/following::span[1]</value>
      <webElementGuid>7caf6d34-5b3e-47fc-b8e3-c43546158277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aggregated sub companies'])[1]/following::span[1]</value>
      <webElementGuid>627352b0-3a61-4bdc-9de6-47ec260a67f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adesso'])[1]/preceding::span[1]</value>
      <webElementGuid>48d3ec2e-4776-4eda-aedb-8d09b5df2a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AlmavivA'])[1]/preceding::span[2]</value>
      <webElementGuid>89b2dc18-9de5-4194-9fc2-6298d8f0269d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accenture']/parent::*</value>
      <webElementGuid>a0cd6069-e848-413d-9e8a-3fb465534a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>5ee0cf65-350c-4fc0-8c3e-01bd5c51a7de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Accenture' or . = 'Accenture')]</value>
      <webElementGuid>c7207e7e-081d-436a-8654-451b3a703466</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
