<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Adobe</name>
   <tag></tag>
   <elementGuidId>40479cb4-650d-4789-957c-96176f4ba967</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mip-competitors-landing__table-section__name-column__name__label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Revenue (last updated)'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e605aef7-101f-4d2b-bc9c-bb9ba0a16a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mip-competitors-landing__table-section__name-column__name__label</value>
      <webElementGuid>cd8f67e2-b5b4-43af-a4be-cc7a6697aaa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adobe</value>
      <webElementGuid>b97270bc-1053-4c6d-9e52-e585dc330613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;mip-app&quot;]/div[@class=&quot;mip-app__main-row&quot;]/div[@class=&quot;mip-app__main-row__main-column&quot;]/div[@class=&quot;mip-app__main-row__main-column__content&quot;]/mip-companies[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mip-dashboard mip-competitors-landing&quot;]/div[@class=&quot;mip-dashboard__row--biggest&quot;]/mip-section[@class=&quot;mip-section--big landing mip-competitors-landing__table-section&quot;]/div[@class=&quot;mip-section mip-section--big&quot;]/div[@class=&quot;mip-table ng-star-inserted&quot;]/div[@class=&quot;tableContainer&quot;]/mip-table[@class=&quot;ng-tns-c125-1 ng-star-inserted&quot;]/table[@class=&quot;mat-table cdk-table mat-sort ng-tns-c125-1 mip-table&quot;]/tbody[1]/tr[@class=&quot;mat-row cdk-row ng-tns-c125-1 ng-star-inserted&quot;]/td[@class=&quot;mat-cell cdk-cell cdk-column-organizationName mat-column-organizationName ng-tns-c125-1 ng-star-inserted&quot;]/div[@class=&quot;mip-competitors-landing__table-section__name-column ng-star-inserted&quot;]/a[@class=&quot;mip-competitors-landing__table-section__name-column__name&quot;]/span[@class=&quot;mip-competitors-landing__table-section__name-column__name__label&quot;]</value>
      <webElementGuid>d08d842a-6af3-40cb-9f5e-77405520b6ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revenue (last updated)'])[1]/following::span[1]</value>
      <webElementGuid>2ad9f1db-7601-4bfb-b155-0a527cc87586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aggregated sub companies'])[1]/following::span[1]</value>
      <webElementGuid>baca1fec-d0f5-4b9c-bfe9-6a7faf3dcefb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amazon Web Services'])[1]/preceding::span[1]</value>
      <webElementGuid>3753f9ea-a861-4aaf-86f3-df55945ab9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Appian'])[1]/preceding::span[2]</value>
      <webElementGuid>30e233c9-2a50-4b58-8b84-6dee5e5cdba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Adobe']/parent::*</value>
      <webElementGuid>bb3bb132-a3c9-4676-821a-2a309d063631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>1fa9653c-e9ea-4950-96e9-3d7927035505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Adobe' or . = 'Adobe')]</value>
      <webElementGuid>2e626a3e-0306-4c20-a93e-7edd550f9d7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
