<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_I have read the Terms of use</name>
   <tag></tag>
   <elementGuidId>5af9db23-f963-4e9a-bbc5-0e94922cb9b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-checkbox[@id='terms']/label/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.mat-checkbox-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1e797a56-1f0c-44d0-9cca-f7e403561529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-checkbox-label</value>
      <webElementGuid>bec6535a-e8e5-4d22-8c82-f168250e1465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  I have read the Terms of use.</value>
      <webElementGuid>80eb1d98-606c-49fb-a331-d54f693c062a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;terms&quot;)/label[@class=&quot;mat-checkbox-layout&quot;]/span[@class=&quot;mat-checkbox-label&quot;]</value>
      <webElementGuid>16ca2a8c-6d81-4afb-a7be-e5bf2f17c015</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='terms']/label/span[2]</value>
      <webElementGuid>851d35c0-cdb4-471a-9bcd-905c101a16af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms and Conditions'])[1]/following::span[7]</value>
      <webElementGuid>49e7a8f8-a3d9-406c-ac6c-06eaa3970f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporate Research Unit'])[1]/following::span[7]</value>
      <webElementGuid>7fbfd0b4-6279-40f7-aed1-8bdb02d888f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='I have read the']/parent::*</value>
      <webElementGuid>525d1516-0463-41dc-8af9-8095d5e36505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>84390e23-cafb-462d-91e7-b57a629083af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '  I have read the Terms of use.' or . = '  I have read the Terms of use.')]</value>
      <webElementGuid>78cfe588-a344-4020-97fb-bc67978ebdf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
