<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Financial Modeling Prep_search-box</name>
   <tag></tag>
   <elementGuidId>d632ef02-5287-4811-879c-dbb282fa381b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54261fc6-306e-44eb-bca5-89704f22d928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search stock...</value>
      <webElementGuid>05d8a687-545f-415f-bb29-c3bebac37c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search for stock information</value>
      <webElementGuid>d76d99b0-e4d8-4e3a-be54-b29a58e537dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-box</value>
      <webElementGuid>a0cee953-1365-4ed1-8495-36b8e980457e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-fmp&quot;)/div[@class=&quot;burger-menu&quot;]/div[2]/div[@class=&quot;stock-search-component-small&quot;]/div[@class=&quot;stock-search&quot;]/input[@class=&quot;search-box&quot;]</value>
      <webElementGuid>c111de67-f53e-4b9a-aa91-7ab2688e6eda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>73344fe2-42b5-46b1-bd59-6c1b14ebed84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbar-fmp']/div[2]/div[2]/div/div/input</value>
      <webElementGuid>d1f40a76-7705-4e92-a63c-228c8e3eeca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>37a910c8-0af8-4763-837e-9097da8f1bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search stock...' and @title = 'Search for stock information']</value>
      <webElementGuid>e98ee8f0-be62-4aae-bfa9-45c12b185c61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
