<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Adobe_actualizado</name>
   <tag></tag>
   <elementGuidId>0dc73a2f-d86d-4e59-a5b6-8fbdea7070ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='pr_id_1-table']/tbody/tr/td/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.mip-competitors-landing__table-section__name-column__name__label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>70666a2d-4ed5-4dd8-a10a-ba0b2183ba55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mip-competitors-landing__table-section__name-column__name__label</value>
      <webElementGuid>6cc512bc-8ec5-44c3-9637-e59ccca1cb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adobe</value>
      <webElementGuid>f1d094dd-d260-493d-be04-c94f88da2d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_1-table&quot;)/tbody[@class=&quot;p-element p-datatable-tbody&quot;]/tr[@class=&quot;p-selectable-row ng-star-inserted&quot;]/td[@class=&quot;p-element ui-resizable-column ng-star-inserted&quot;]/div[@class=&quot;mip-competitors-landing__table-section__name-column ng-star-inserted&quot;]/a[@class=&quot;mip-competitors-landing__table-section__name-column__name&quot;]/span[@class=&quot;mip-competitors-landing__table-section__name-column__name__label&quot;]</value>
      <webElementGuid>f975014f-99b0-43db-aaf4-4469d0ad6f14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pr_id_1-table']/tbody/tr/td/div/a/span</value>
      <webElementGuid>fddda5ee-906e-438b-883c-76e252df90fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revenue (last updated)'])[1]/following::span[2]</value>
      <webElementGuid>e96f6b7c-2bdb-44a1-b6d8-d6eec3add8a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aggregated sub companies'])[1]/following::span[4]</value>
      <webElementGuid>06338ad0-b8bf-4e2f-b1d2-df13ef9c626b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='see more'])[1]/preceding::span[1]</value>
      <webElementGuid>1b3f314f-585b-44ab-8dd8-f04d72f3dca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='see more'])[2]/preceding::span[2]</value>
      <webElementGuid>df1f59df-358d-4981-b6c0-770908b42fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Adobe']/parent::*</value>
      <webElementGuid>70abdc11-8abd-47a4-9358-1c750a5d1b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>7367b422-5947-4cd4-b519-3f43f005031a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Adobe' or . = 'Adobe')]</value>
      <webElementGuid>4fef3aa2-e0fe-4584-ab83-c9554a1ec383</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
