<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_17.606.000.000</name>
   <tag></tag>
   <elementGuidId>e8964440-8941-481d-b61f-68d72584580d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='pr_id_12-table']/tbody/tr/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pr_id_12-table > tbody.p-element.p-datatable-tbody > tr.p-selectable-row.ng-star-inserted > td.p-element.ui-resizable-column.currency.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>92b80e52-e95c-45e3-a900-975775738a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alignfrozen</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>fdf64958-211b-4f4b-b842-61f8e4d44540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element ui-resizable-column currency ng-star-inserted</value>
      <webElementGuid>8ac30c70-c9ed-466d-93f4-660200b53afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 17.606.000.000 $ </value>
      <webElementGuid>debb362e-d1f8-46aa-b48a-6c0dd167a852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_12-table&quot;)/tbody[@class=&quot;p-element p-datatable-tbody&quot;]/tr[@class=&quot;p-selectable-row ng-star-inserted&quot;]/td[@class=&quot;p-element ui-resizable-column currency ng-star-inserted&quot;]</value>
      <webElementGuid>390fab91-fbae-40a0-8e5e-461e3d534b92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pr_id_12-table']/tbody/tr/td[2]</value>
      <webElementGuid>a5de75ee-a8a7-41b1-8869-9c21ce1ea4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Net income per employee'])[1]/following::td[2]</value>
      <webElementGuid>dd90f2ee-8dc9-40cc-9e2c-4f2d2c1d7efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revenue per employee'])[1]/following::td[2]</value>
      <webElementGuid>df307bbe-42d2-4a98-9062-c23ad616f433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Source:'])[3]/preceding::td[19]</value>
      <webElementGuid>bb9176ed-01b2-4e49-aa40-408a9a5a69b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mip-competitors-revenue-per-employee-table/div/mip-table-ng-prime/div/p-table/div/div/table/tbody/tr/td[2]</value>
      <webElementGuid>589bc4f8-1d7d-4743-b038-ab204ad3c1e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = ' 17.606.000.000 $ ' or . = ' 17.606.000.000 $ ')]</value>
      <webElementGuid>fcd8d136-8f18-49bb-a552-e6c94f263857</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
