<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_apartmentCompaniesexpand_more</name>
   <tag></tag>
   <elementGuidId>3daea126-3197-417d-9d72-1606a35c3e4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Market Landscape'])[1]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>78cd36d4-52c4-40a2-a64c-b208b2008f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c63-0 mip-menu__section__item__menu-item</value>
      <webElementGuid>1268b154-4bc1-4674-bba1-281a650cab4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>apartmentCompaniesexpand_more</value>
      <webElementGuid>227dcf6e-ec0c-45ec-985f-9881d1ca23b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;mip-app&quot;]/div[@class=&quot;mip-app__main-row&quot;]/mip-menu[@class=&quot;ng-tns-c63-0&quot;]/div[@class=&quot;ng-tns-c63-0 mip-menu&quot;]/div[@class=&quot;ng-tns-c63-0&quot;]/div[@class=&quot;mip-menu__section ng-tns-c63-0 ng-star-inserted&quot;]/div[@class=&quot;mip-menu__section__item ng-tns-c63-0 ng-star-inserted&quot;]/a[@class=&quot;ng-tns-c63-0 mip-menu__section__item__menu-item&quot;]</value>
      <webElementGuid>128870e5-a8ba-4220-8efa-0ee5d18ae11f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Market Landscape'])[1]/following::a[1]</value>
      <webElementGuid>9c260eea-51f9-48ce-893e-44f9a414ca5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Market Information'])[1]/following::a[2]</value>
      <webElementGuid>0177d873-5fbe-4590-80fb-7bc5e7b21fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Competitors'])[1]/preceding::a[1]</value>
      <webElementGuid>2d79c186-6470-4200-9b2d-ae561d4d46ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>02ff73d1-8d57-40f2-8878-e9888555c3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'apartmentCompaniesexpand_more' or . = 'apartmentCompaniesexpand_more')]</value>
      <webElementGuid>be307e7d-c451-476f-a6bc-a196a1f61f5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
