<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AXA MEDITERRANEAN SYSTEMS,A.E.I.E.,SUCURSAL EM PORTUGAL</name>
   <tag></tag>
   <elementGuidId>42ad2c45-9754-4c7f-b9e4-39b430c3fd9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[3]/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a0bd8259-7f2a-4117-92e8-3535315336ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>3ae88889-5739-491a-b1ad-c9a6bc4b1dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://emeal.cloudknowler365.com/detail/http:%2F%2Fwww.knowler.com%2Fontology%2Fcore%2FOrganization/http:%2F%2Fwww.knowler.com%2Fontology%2Fcore%2Fparty-o-0-4000085351</value>
      <webElementGuid>71365f76-3573-4c08-932e-1203387a25eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>70700ccd-ec62-4c6f-a1c5-06f7da334f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AXA MEDITERRANEAN SYSTEMS,A.E.I.E.,SUCURSAL EM PORTUGAL</value>
      <webElementGuid>29c8ee42-a9ee-4d6f-83b9-2dcdfae28433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_9-table&quot;)/tbody[@class=&quot;p-element p-datatable-tbody&quot;]/tr[@class=&quot;p-selectable-row ng-star-inserted&quot;]/td[@class=&quot;p-element ui-resizable-column ng-star-inserted&quot;]/span[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;link&quot;]</value>
      <webElementGuid>d38e0919-497d-46c1-897e-791f0d3adba5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pr_id_9-table']/tbody/tr/td[3]/span/a</value>
      <webElementGuid>3d46cc1a-96ef-4c6e-b6fe-d370f26c1916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AXA MEDITERRANEAN SYSTEMS,A.E.I.E.,SUCURSAL EM PORTUGAL')]</value>
      <webElementGuid>710b7fec-ec85-459d-92d1-12e7c9acab4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[AXA] Bolsa Horas TFS'])[1]/following::a[1]</value>
      <webElementGuid>fad38aac-25e8-40f7-80fc-4bdfe63c8635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub-Service line'])[1]/following::a[2]</value>
      <webElementGuid>f8eb972a-c5a7-4c66-92d0-afe941c253c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='calendar_today'])[1]/preceding::a[1]</value>
      <webElementGuid>02e3ceff-331e-4274-8989-28e16f684eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Closed Project'])[1]/preceding::a[1]</value>
      <webElementGuid>a61defa0-c66b-4542-8e39-304b4403f5ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AXA MEDITERRANEAN SYSTEMS,A.E.I.E.,SUCURSAL EM PORTUGAL']/parent::*</value>
      <webElementGuid>ae65c956-0c09-4f8e-af0c-a5a725034365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://emeal.cloudknowler365.com/detail/http:%2F%2Fwww.knowler.com%2Fontology%2Fcore%2FOrganization/http:%2F%2Fwww.knowler.com%2Fontology%2Fcore%2Fparty-o-0-4000085351')]</value>
      <webElementGuid>c8e8bfd6-a84c-45bb-98db-c39caea10a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/span/a</value>
      <webElementGuid>f894f875-84c1-4808-bfc8-5b9590866a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://emeal.cloudknowler365.com/detail/http:%2F%2Fwww.knowler.com%2Fontology%2Fcore%2FOrganization/http:%2F%2Fwww.knowler.com%2Fontology%2Fcore%2Fparty-o-0-4000085351' and (text() = 'AXA MEDITERRANEAN SYSTEMS,A.E.I.E.,SUCURSAL EM PORTUGAL' or . = 'AXA MEDITERRANEAN SYSTEMS,A.E.I.E.,SUCURSAL EM PORTUGAL')]</value>
      <webElementGuid>d2b6c525-942f-4867-a22e-066e9b136503</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
