<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>723e5f70-51f8-4516-ab3a-02cd9e6d5cb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-1']/mip-onboarding-offering_capabilities/div/div/div/div/mip-button/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mip-onboarding__buttons.ng-star-inserted > mip-button > button.mip-button.mip-button--primary.mip-button--big</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>131aead7-a201-485e-9de2-e951ad945057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mip-button mip-button--primary mip-button--big</value>
      <webElementGuid>b0b085c1-5509-4a7e-b8ac-9ef65356b8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Next </value>
      <webElementGuid>bd909048-bdf9-43d4-b2c6-9cad9de2d094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-1&quot;)/mip-onboarding-offering_capabilities[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mip-onboarding&quot;]/div[@class=&quot;mip-onboarding__main-content__single-content&quot;]/div[@class=&quot;mip-onboarding__margin&quot;]/div[@class=&quot;mip-onboarding__buttons ng-star-inserted&quot;]/mip-button[1]/button[@class=&quot;mip-button mip-button--primary mip-button--big&quot;]</value>
      <webElementGuid>d1162664-3b67-4c2f-aac0-484f0ee0278c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-1']/mip-onboarding-offering_capabilities/div/div/div/div/mip-button/button</value>
      <webElementGuid>53f2a514-6e28-4ff6-9a24-a82fee45cf5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Global Portfolio'])[2]/following::button[1]</value>
      <webElementGuid>5e808eb4-c387-41de-b407-9b65bb56f74f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Offering &amp; Capabilities'])[3]/following::button[1]</value>
      <webElementGuid>6114ed8a-34b3-4ea7-a586-580a3249e0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
      <webElementGuid>1274193e-6be2-4cfe-8c7b-3ffc0cb624af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::button[1]</value>
      <webElementGuid>ad5f0e97-2728-4871-8765-4270062d24ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>693c0391-5583-4a9d-80bb-777dcac90b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/mip-button/button</value>
      <webElementGuid>4911df31-e7fa-4154-9ff6-ae2db777a695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Next ' or . = ' Next ')]</value>
      <webElementGuid>d314991d-d844-4add-b5b2-1a2fc9f983a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
