<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_cases</name>
   <tag></tag>
   <elementGuidId>a66e67c9-2bf5-432d-9260-f3c377be3f32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Project name'])[1]/preceding::mat-icon[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mat-tooltip-trigger.mip-nav-bar__link.ng-star-inserted.mip-nav-bar__link--active > mat-icon.mat-icon.notranslate.material-icons-outlined.mat-icon-no-color.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>50abd64f-dded-42e4-a34c-0968aedd8f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c9ab5ed5-8674-4f00-a6fd-27e22c5b08e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate material-icons-outlined mat-icon-no-color ng-star-inserted</value>
      <webElementGuid>52631266-652c-4c45-bb0f-6a8ca3731da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>66504fc0-ef0a-4d72-8f54-f4d8178b47ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>2b461651-0a6a-43f9-b70d-9e2c8bf3151f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-namespace</name>
      <type>Main</type>
      <value>material-icons-outlined</value>
      <webElementGuid>100ffa4a-0711-4473-9851-fc6040e47eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>cases</value>
      <webElementGuid>addb0114-0c36-45aa-a90a-9368aaed10f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;mip-app&quot;]/div[@class=&quot;mip-app__main-row&quot;]/div[@class=&quot;mip-app__main-row__main-column&quot;]/div[@class=&quot;mip-app__main-row__main-column__content&quot;]/mip-offering-capabilities[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mip-page-header&quot;]/mip-nav-bar[@class=&quot;mip-market-landscape__nav-bar&quot;]/div[@class=&quot;mip-nav-bar mip-nav-bar__principal&quot;]/a[@class=&quot;mat-tooltip-trigger mip-nav-bar__link ng-star-inserted mip-nav-bar__link--active&quot;]/mat-icon[@class=&quot;mat-icon notranslate material-icons-outlined mat-icon-no-color ng-star-inserted&quot;]</value>
      <webElementGuid>2f63738b-6cd5-4b31-aabe-a11eeeac0ca5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project name'])[1]/preceding::mat-icon[2]</value>
      <webElementGuid>8136567a-ed18-47d7-8282-50d6c4096d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='cases']/parent::*</value>
      <webElementGuid>cf94eeb0-1f80-4817-b8e2-05fcec58a1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/mat-icon</value>
      <webElementGuid>adb6f7f4-7336-4cf2-9c59-30ae4970d47b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'cases' or . = 'cases')]</value>
      <webElementGuid>d7f79d87-4e1d-4dbd-b1f9-e1cc53e95731</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
