<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_navigate_before</name>
   <tag></tag>
   <elementGuidId>34a5dfd9-bdaf-416a-9b0a-c089674d5be4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::mat-icon[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.mip-menu__collapse-item__button__icon.ng-tns-c63-0.material-icons.mat-ligature-font.mat-icon-no-color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>1d826ac5-0d9f-4a2a-b8f8-4f99aad48854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e4e9a16d-fdb7-4d33-a28e-75ea7d9187cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate mip-menu__collapse-item__button__icon ng-tns-c63-0 material-icons mat-ligature-font mat-icon-no-color</value>
      <webElementGuid>0eb9c35f-dfbb-4975-afa5-33b41ee08209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6b3cbca1-eb35-414d-a8fa-0fb486bb0643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>b025be5e-c998-4ab0-82a8-b123d2067482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>navigate_before</value>
      <webElementGuid>d4a1fe19-40e0-4b9f-907f-8f1d92e72e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;mip-app&quot;]/div[@class=&quot;mip-app__main-row&quot;]/mip-menu[@class=&quot;ng-tns-c63-0&quot;]/div[@class=&quot;ng-tns-c63-0 mip-menu mip-menu--collapse&quot;]/div[@class=&quot;ng-tns-c63-0&quot;]/div[@class=&quot;mip-menu__collapse-item ng-tns-c63-0&quot;]/div[@class=&quot;mip-menu__collapse-item__button ng-tns-c63-0&quot;]/mat-icon[@class=&quot;mat-icon notranslate mip-menu__collapse-item__button__icon ng-tns-c63-0 material-icons mat-ligature-font mat-icon-no-color&quot;]</value>
      <webElementGuid>3ec3582a-31d0-415f-b3be-c2aa74bd77a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::mat-icon[2]</value>
      <webElementGuid>da216642-eb79-4d48-b9e6-7a99fe4e2633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='by NTT DATA'])[1]/following::mat-icon[4]</value>
      <webElementGuid>b5111004-3ca9-4066-adf5-a5b23c1efd56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::mat-icon[3]</value>
      <webElementGuid>06e3c151-115c-41b4-a886-f6e09715562e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Market Information'])[1]/preceding::mat-icon[3]</value>
      <webElementGuid>fdbb33df-ec56-46a8-9ddf-2479c8e8c22a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='navigate_before']/parent::*</value>
      <webElementGuid>a95788b1-8686-40cc-af9e-2760a916def9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/mat-icon</value>
      <webElementGuid>13b5ae73-3676-4a2a-ab9f-5733b1d6f335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'navigate_before' or . = 'navigate_before')]</value>
      <webElementGuid>e1925ca3-c3b7-4792-880a-2d40c582a0c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
