<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Agility, Connectivity, Data control</name>
   <tag></tag>
   <elementGuidId>011dbaf0-0775-4a26-8265-c34ac78f9ab8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='pr_id_3-table']/tbody/tr/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c24439d6-bf5d-4f1b-a59a-217b6087d7c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alignfrozen</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>06fb7861-ebc6-47ea-839a-6fe2f0e62255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element ui-resizable-column ng-star-inserted</value>
      <webElementGuid>d789ecb3-c3c6-4118-8557-6781ed096d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Agility, Connectivity, Data control </value>
      <webElementGuid>9e6444af-0d21-4ac7-9383-da95878b5a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_3-table&quot;)/tbody[@class=&quot;p-element p-datatable-tbody&quot;]/tr[@class=&quot;p-selectable-row ng-star-inserted&quot;]/td[@class=&quot;p-element ui-resizable-column ng-star-inserted&quot;]</value>
      <webElementGuid>045c8577-cc30-4696-a261-d501948c9c35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pr_id_3-table']/tbody/tr/td[3]</value>
      <webElementGuid>ccaa921b-769c-4801-9d97-6ab0ce5e7e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALONDRA'])[1]/following::td[1]</value>
      <webElementGuid>901a136b-de2b-407d-9e81-4a64693c9f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Success cases'])[1]/following::td[3]</value>
      <webElementGuid>c471b49d-f151-4d80-a0fc-2cda9c6d06bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SaaS'])[1]/preceding::td[1]</value>
      <webElementGuid>6ae27b27-7917-4ca4-886e-570d49a83a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insurance'])[2]/preceding::td[2]</value>
      <webElementGuid>eb3402e3-2332-49cb-929e-359045cb1635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agility, Connectivity, Data control']/parent::*</value>
      <webElementGuid>33a7db80-a783-417f-b2c6-bf3106dcfd36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>510cc2d9-e4d0-4a23-9bc8-8dc0f5ea080a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = ' Agility, Connectivity, Data control ' or . = ' Agility, Connectivity, Data control ')]</value>
      <webElementGuid>3913b1e5-148e-48fd-b034-a198f9d10ddc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
