<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Insurance</name>
   <tag></tag>
   <elementGuidId>f746e7f3-9826-48a3-8989-16a755505cec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='pr_id_3-table']/tbody/tr/td[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>400bc43a-8e91-482f-8fc8-8f190b622466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alignfrozen</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>8903c265-488d-445b-9f85-81d3d77253ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element ui-resizable-column ng-star-inserted</value>
      <webElementGuid>50ba9ff2-adac-4a6b-bad6-e79d419ad383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Insurance </value>
      <webElementGuid>43288a40-bc40-4319-9af5-e17eb8dd56b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_3-table&quot;)/tbody[@class=&quot;p-element p-datatable-tbody&quot;]/tr[@class=&quot;p-selectable-row ng-star-inserted&quot;]/td[@class=&quot;p-element ui-resizable-column ng-star-inserted&quot;]</value>
      <webElementGuid>1988f813-d648-4d51-bd1d-534990feefc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pr_id_3-table']/tbody/tr/td[5]</value>
      <webElementGuid>4090e0bb-fdb2-4520-a158-c091f272ea10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SaaS'])[1]/following::td[1]</value>
      <webElementGuid>ca453878-67b1-4d96-8c3d-bbe13848717b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agility, Connectivity, Data control'])[1]/following::td[2]</value>
      <webElementGuid>5ae24dbc-0072-411a-a10e-87fc6eccd7ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='account_circle'])[1]/preceding::td[1]</value>
      <webElementGuid>befa7085-f925-468b-a253-38058ef3609b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jordi Serrado Escriu'])[1]/preceding::td[1]</value>
      <webElementGuid>a3e59ab7-9960-4c3a-a41d-54ad9d5f05a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]</value>
      <webElementGuid>565acdac-ee04-4b0b-a035-c162d3c0b0e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = ' Insurance ' or . = ' Insurance ')]</value>
      <webElementGuid>245bb13b-0dc7-4b9d-b25b-3e8580c0bda2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
