<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_61,594,305</name>
   <tag></tag>
   <elementGuidId>b0443aa8-43f9-40f7-a1d1-d1edc6bb01fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='incomeStatement']/div[2]/table/tbody/tr/td/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1a106121-cab0-495d-9f32-4eabd9505d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						61,594,305
					</value>
      <webElementGuid>cf3b81e0-c595-4a54-a05f-3eee8fcafed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;incomeStatement&quot;)/div[@class=&quot;table-wrapper&quot;]/table[@class=&quot;table table-striped table-sort&quot;]/tbody[1]/tr[1]/td[1]/span[1]</value>
      <webElementGuid>90eaf51d-4b37-482b-b1a9-04bf2efce9f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incomeStatement']/div[2]/table/tbody/tr/td/span</value>
      <webElementGuid>39d00194-c874-4274-a322-4122d658a5d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revenue'])[1]/following::span[1]</value>
      <webElementGuid>691bd0b4-fc2b-48cc-b0b9-329dc25f1afe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XLSX'])[5]/following::span[2]</value>
      <webElementGuid>dcc2ed7b-add6-438c-95b7-a1f5bb10c37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cost of Revenue'])[1]/preceding::span[5]</value>
      <webElementGuid>b4eb24d6-6359-4a41-9be3-8519656a9429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gross Profit'])[1]/preceding::span[11]</value>
      <webElementGuid>17d360f9-5bb9-48d9-8c10-c64ff6725d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='61,594,305']/parent::*</value>
      <webElementGuid>6182388d-dfc9-4cec-97d2-5bf6c7c9887b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span</value>
      <webElementGuid>41ce3b57-00ac-48c8-a39b-47996f9b2824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
						61,594,305
					' or . = '
						61,594,305
					')]</value>
      <webElementGuid>4d6625b0-bd7d-4206-bc97-8d0266032937</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
