<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_3,268,121</name>
   <tag></tag>
   <elementGuidId>3dff2f0d-9294-4cbe-94a3-fc0788fb3beb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='incomeStatement']/div[2]/table/tbody/tr[12]/td[4]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4dd47e3e-d480-454e-88ec-87fbd62f78f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						3,268,121
					</value>
      <webElementGuid>186056d6-46ea-4f3a-9131-55a17638b5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;incomeStatement&quot;)/div[@class=&quot;table-wrapper&quot;]/table[@class=&quot;table table-striped table-sort&quot;]/tbody[1]/tr[12]/td[4]/span[1]</value>
      <webElementGuid>e5c8c21d-c12f-4a61-bd99-e20b68b7bc04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incomeStatement']/div[2]/table/tbody/tr[12]/td[4]/span</value>
      <webElementGuid>13520f6f-94af-4f91-8603-e7e7b34ca52b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operating Income'])[1]/following::span[4]</value>
      <webElementGuid>d7126654-4670-4d35-a1d9-0c48c6e885e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cost and Expenses'])[1]/following::span[10]</value>
      <webElementGuid>1310bddf-baea-466a-bde7-edaae0ea7cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interest Expense'])[1]/preceding::span[2]</value>
      <webElementGuid>4a70db6a-afe0-4e83-ae22-6a3b415d8369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Income Tax Expense'])[1]/preceding::span[8]</value>
      <webElementGuid>150e54ef-9114-4d4c-a17c-f9a0139dabcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3,268,121']/parent::*</value>
      <webElementGuid>f826afe8-a009-43b7-9eda-06b1c9b85c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td[4]/span</value>
      <webElementGuid>adafbf65-d513-40f0-8244-8dcec9b09cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
						3,268,121
					' or . = '
						3,268,121
					')]</value>
      <webElementGuid>34f8e803-7fd1-4290-96db-e43a5b110425</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
