<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_7,835,009</name>
   <tag></tag>
   <elementGuidId>59bb0d12-ec9d-4d86-a360-047f68c5feb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='incomeStatement']/div[2]/table/tbody/tr[3]/td[5]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b42f18c1-41cb-4143-be51-b8acdd31e399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						7,835,009
					</value>
      <webElementGuid>edb93902-e456-4206-923d-4f0430b5e11c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;incomeStatement&quot;)/div[@class=&quot;table-wrapper&quot;]/table[@class=&quot;table table-striped table-sort&quot;]/tbody[1]/tr[3]/td[5]/span[1]</value>
      <webElementGuid>70f24543-4c4f-4bde-9807-1efdae03972a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='incomeStatement']/div[2]/table/tbody/tr[3]/td[5]/span</value>
      <webElementGuid>007ad081-8379-49b0-b060-bd7c54f5bfef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gross Profit'])[1]/following::span[5]</value>
      <webElementGuid>d367a8b0-ad97-4d94-9ef0-303cd8ab5759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cost of Revenue'])[1]/following::span[11]</value>
      <webElementGuid>85a90792-37e0-424d-a327-b581de90629f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operating Expenses'])[1]/preceding::span[1]</value>
      <webElementGuid>ecf0a4f9-8a30-401f-8c7c-daec06453a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selling, General and Administrative Expenses'])[1]/preceding::span[7]</value>
      <webElementGuid>884f19ac-e4e0-4886-a489-47c4d3606b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='7,835,009']/parent::*</value>
      <webElementGuid>3f6e99d2-2651-4e34-b933-24a4efd918b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]/span</value>
      <webElementGuid>69ef601c-02f5-45d7-bfb1-1ff5f8d1b60d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
						7,835,009
					' or . = '
						7,835,009
					')]</value>
      <webElementGuid>6f7e688d-19ed-4349-8701-0f2dd9510098</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
