<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ADBE Adobe Inc</name>
   <tag></tag>
   <elementGuidId>9537c8d1-061c-4201-bb23-d053fada50aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.search-result-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search-box-result']/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>81296372-9310-443d-be10-c4b4f4d758ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/financial-summary/ADBE</value>
      <webElementGuid>462e57bf-57aa-477a-8ea4-546ac51ae401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>767226d1-c220-4947-abc7-d383f23d1872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-result-item</value>
      <webElementGuid>5b9df061-a1f6-4bd4-8a99-1751a2bdae99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADBE Adobe Inc.
                    </value>
      <webElementGuid>e3004eab-6d07-4a41-a9c6-5ecdbc5c7f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-box-result&quot;)/div[2]/a[@class=&quot;search-result-item&quot;]</value>
      <webElementGuid>c6893fb6-a189-4d3c-a860-c1bb248a6fdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-box-result']/div[2]/a</value>
      <webElementGuid>afb143d3-5940-40be-af6f-ff5622c32ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stocks'])[1]/following::a[1]</value>
      <webElementGuid>097626f4-e4d2-43a9-86b9-57ce31831c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Financial Modeling Prep'])[2]/following::a[1]</value>
      <webElementGuid>b4d42fb6-a497-4fc1-9be5-13994777caca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Adobe Inc.']/parent::*</value>
      <webElementGuid>4f8f2ec9-021e-4e67-b3c1-84075322b845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/financial-summary/ADBE')]</value>
      <webElementGuid>853ac645-f520-494b-81c7-2d3aaa45d5af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>76bf5d66-d70d-45a6-bb73-5263508999a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/financial-summary/ADBE' and (text() = 'ADBE Adobe Inc.
                    ' or . = 'ADBE Adobe Inc.
                    ')]</value>
      <webElementGuid>2d9943bf-4c9e-458a-867f-4a3b07b1e1ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
