<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Financial Modeling Prep_search-box</name>
   <tag></tag>
   <elementGuidId>d577a435-20da-4f27-89d0-aab232e54e76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>daec98a3-73e2-4ea8-ab4d-f8008dc9b815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search stock...</value>
      <webElementGuid>4ef463b2-613a-4384-b4fb-29472373d399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search for stock information</value>
      <webElementGuid>8e44c99c-ae22-4ba5-9454-43b989090db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-box</value>
      <webElementGuid>dd46acde-478f-47da-a6ad-93cbab07683e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-fmp&quot;)/div[@class=&quot;burger-menu&quot;]/div[2]/div[@class=&quot;stock-search-component-small&quot;]/div[@class=&quot;stock-search&quot;]/input[@class=&quot;search-box&quot;]</value>
      <webElementGuid>7a4c089d-f2a2-4fe6-9d59-1250c7d3d3d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>010cc3ec-0d84-4984-ad97-945b1f3ffe32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbar-fmp']/div[2]/div[2]/div/div/input</value>
      <webElementGuid>8c1d5c8a-588e-4813-8916-7d1e2e390b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>b1377c66-d0e0-4c34-b464-804a0a7b46f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search stock...' and @title = 'Search for stock information']</value>
      <webElementGuid>276a3a48-0748-4f5b-9b75-7f4800be2daf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
