<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_The economy of things (EoT) refers to the use</name>
   <tag></tag>
   <elementGuidId>8dec2d95-544d-4463-90c9-e78cccfe28d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Economy of Things'])[1]/following::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ef5c9377-193f-408f-be31-91ae01cbcc65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mip-innovation-trend__cards__card__body__description</value>
      <webElementGuid>c8c34f1d-2718-4f6e-a23d-5717cc0d3c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The economy of things (EoT) refers to the use of internetconnected devices, such as sensors and other forms of IoT (Internet of Things) technology, to gather data and enable new business models and processes. This can include things like smart cities, connected homes, and industrial IoT applications. The EoT enables new business models by using the data generated by these devices to improve efficiency, reduce costs, and create new revenue streams. Some examples of EoT applications and use cases include: Smart cities, using IoT technologies to improve city services and infrastructure management Industrial IoT, using IoT to improve the efficiency and productivity of manufacturing, transportation and logistics Connected homes, using IoT to improve home automation, energy management and security Predictive maintenance, using IoT to monitor and analyze dataaddsee more</value>
      <webElementGuid>9c3c16ad-e208-402b-9a69-a09cef421ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;mip-app&quot;]/div[@class=&quot;mip-app__main-row&quot;]/div[@class=&quot;mip-app__main-row__main-column&quot;]/div[@class=&quot;mip-app__main-row__main-column__content&quot;]/mip-innovation-trends[@class=&quot;ng-star-inserted&quot;]/mip-innovations-trends-ntt-data[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mip-dashboard&quot;]/div[@class=&quot;mip-dashboard__row--biggest&quot;]/div[@class=&quot;mip-innovation-trend__cards&quot;]/div[@class=&quot;mip-innovation-trend__cards__card ng-star-inserted&quot;]/div[@class=&quot;mip-innovation-trend__cards__card__body&quot;]/div[@class=&quot;mip-innovation-trend__cards__card__body__description&quot;]</value>
      <webElementGuid>9a4b8600-8138-410d-a8e8-6d8b61f10ff7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Economy of Things'])[1]/following::div[1]</value>
      <webElementGuid>7a14357e-75c0-4bb9-86f2-3a3ef80f9677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div[2]</value>
      <webElementGuid>382bd29f-39ca-4084-bfca-7285f64812ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'The economy of things (EoT) refers to the use of internetconnected devices, such as sensors and other forms of IoT (Internet of Things) technology, to gather data and enable new business models and processes. This can include things like smart cities, connected homes, and industrial IoT applications. The EoT enables new business models by using the data generated by these devices to improve efficiency, reduce costs, and create new revenue streams. Some examples of EoT applications and use cases include: Smart cities, using IoT technologies to improve city services and infrastructure management Industrial IoT, using IoT to improve the efficiency and productivity of manufacturing, transportation and logistics Connected homes, using IoT to improve home automation, energy management and security Predictive maintenance, using IoT to monitor and analyze dataaddsee more' or . = 'The economy of things (EoT) refers to the use of internetconnected devices, such as sensors and other forms of IoT (Internet of Things) technology, to gather data and enable new business models and processes. This can include things like smart cities, connected homes, and industrial IoT applications. The EoT enables new business models by using the data generated by these devices to improve efficiency, reduce costs, and create new revenue streams. Some examples of EoT applications and use cases include: Smart cities, using IoT technologies to improve city services and infrastructure management Industrial IoT, using IoT to improve the efficiency and productivity of manufacturing, transportation and logistics Connected homes, using IoT to improve home automation, energy management and security Predictive maintenance, using IoT to monitor and analyze dataaddsee more')]</value>
      <webElementGuid>ee766391-99a5-42a4-9946-db2e1a1d624a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
