<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Accenture to acquire SKS Group_Uptodate</name>
   <tag></tag>
   <elementGuidId>bd371658-4cd6-4cee-9e16-720d73a91158</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div/div/article/div/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.title-section</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>e02aadbd-9ea0-4320-9154-7e76d1d2d8d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title-section</value>
      <webElementGuid>ee33279f-47af-4f8b-8b9f-e2149dce8710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accenture to acquire SKS Group</value>
      <webElementGuid>bf32adf9-6f5d-43e1-854b-2aebbbdb78eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;App&quot;]/div[@class=&quot;content&quot;]/div[1]/div[@class=&quot;container lefted&quot;]/article[@class=&quot;grid article-detail&quot;]/div[@class=&quot;grid-column grid-column-size-2 center-column&quot;]/div[1]/h2[@class=&quot;title-section&quot;]</value>
      <webElementGuid>d4cb1bc9-332f-4769-bcf7-b5f9c61c8861</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/article/div/div/h2</value>
      <webElementGuid>7def5c44-87fa-4877-b5b0-bd3a6335d74d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search tip'])[1]/following::h2[1]</value>
      <webElementGuid>1f829ca6-7a36-4259-9a17-ba682ecf3d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search in archive'])[1]/following::h2[1]</value>
      <webElementGuid>64a71daa-96a8-4e9f-ac16-fc6f77578cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read in original source'])[1]/preceding::h2[1]</value>
      <webElementGuid>866c9e8f-7537-4908-8a70-cafca674774f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[1]/preceding::h2[1]</value>
      <webElementGuid>8f1488dc-3345-4669-a462-3c0b351b4644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>4c50883d-2c32-4c9d-a41b-97bd312fb3d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Accenture to acquire SKS Group' or . = 'Accenture to acquire SKS Group')]</value>
      <webElementGuid>99714bdd-adee-4e84-b345-1e9560db073a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
